/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JsonDataViewer {
        /**
          * @default []
         */
        "data": any[];
        /**
          * @default []
         */
        "hiddenColumns": string[];
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default [5, 10, 25]
         */
        "pageSizeOptions": number[];
        /**
          * @default 10
         */
        "rowsPerPage": number;
    }
    interface JsonViewer {
        /**
          * The JSON data to display
         */
        "data": any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJsonDataViewerElement extends Components.JsonDataViewer, HTMLStencilElement {
    }
    var HTMLJsonDataViewerElement: {
        prototype: HTMLJsonDataViewerElement;
        new (): HTMLJsonDataViewerElement;
    };
    interface HTMLJsonViewerElement extends Components.JsonViewer, HTMLStencilElement {
    }
    var HTMLJsonViewerElement: {
        prototype: HTMLJsonViewerElement;
        new (): HTMLJsonViewerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "json-data-viewer": HTMLJsonDataViewerElement;
        "json-viewer": HTMLJsonViewerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JsonDataViewer {
        /**
          * @default []
         */
        "data"?: any[];
        /**
          * @default []
         */
        "hiddenColumns"?: string[];
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default [5, 10, 25]
         */
        "pageSizeOptions"?: number[];
        /**
          * @default 10
         */
        "rowsPerPage"?: number;
    }
    interface JsonViewer {
        /**
          * The JSON data to display
         */
        "data"?: any;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "json-data-viewer": JsonDataViewer;
        "json-viewer": JsonViewer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "json-data-viewer": LocalJSX.JsonDataViewer & JSXBase.HTMLAttributes<HTMLJsonDataViewerElement>;
            "json-viewer": LocalJSX.JsonViewer & JSXBase.HTMLAttributes<HTMLJsonViewerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
